### ISSUE TITLE
Help : How to add key-value pairs into the CACHES setting ?

### ISSUE THREAD

**Issue by davidfischer-ch** [django-compressor/django-appconf#10]
I want to improve django-imagefit (https://github.com/davidfischer-ch/django-imagefit) to make it use appconf because at the moment this project overrides the value of CACHES (at least) !

Do you have an advice in what is the best way with appconf to set the default value for a key of CACHES e.g. `CACHES ['imagefit'] = default_value` ?

I founded this solution that seem too complicated for such a case : https://github.com/matthewwithanm/django-imagekit/blob/develop/imagekit/conf.py

Also another question, how do you'll implement this (line 42-44 of imagefit's conf.py) : 

    # ConditionalGetMiddleware is required for browser caching
    if not 'django.middleware.http.ConditionalGetMiddleware' in settings.MIDDLEWARE_CLASSES:
        settings.MIDDLEWARE_CLASSES += ('django.middleware.http.ConditionalGetMiddleware',)
Thanks.

**Comment by vaibhav-jain** [comment]
@davidfischer-ch did you found solution ??Please share your findings

**Comment by carltongibson** [comment]
I'm going to close this as it's not actually an issue with AppConf. See the [Usage docs](http://django-appconf.readthedocs.org/en/latest/usage/) — the [Custom Configuration section](http://django-appconf.readthedocs.org/en/latest/usage/#custom-configuration) should give you something to go on.
