### ISSUE TITLE
Error when using django-related imports in settings.py

### ISSUE THREAD

**Issue by panosmm** [django-compressor/django-appconf#13]
Hi, thanks for a great app
I get the problem mentioned here:
https://github.com/django-compressor/django-compressor/issues/333
and here:
https://github.com/django-compressor/django-compressor/issues/273

I traced it to the appconf application, AppConfOptions, line:
    self.holder_path = getattr(meta, 'holder', 'django.conf.settings')

The problem is that in my project I set DJANGO_SETTINGS_MODULE to a local settings file
(I use different settings in local and production)
the problem disappears when I change 'django.conf.settings' to my local settings file. Should the app check the DJANGO_SETTINGS_MODULE var, instead of assuming it's 'django.conf.settings'?

**Comment by nferrari** [comment]
+1

I tried to set the holder attribute in django-compressor (see my PR https://github.com/django-compressor/django-compressor/pull/602), which resolves the problem without modifying django-appconf. However, is does not pass the tests.

Thus, I don't really know if this must be fixed on django-compressor, django-appconf or my own project...

**Comment by carltongibson** [comment]
The main problem I have here is reproducing this. 

Comment from https://github.com/django-compressor/django-compressor/issues/273#issuecomment-13339494

> I found the cause of this - There was some code being called from settings.py which probably led to odd results relating to circular dependencies or something like that.
>
> Moral: Don't do anything in settings.py apart from set settings.

(Largely thinking out loud here)

**Comment by diox** [comment]
Yeah, it happens when you do django-related imports in your `settings.py`. It'd be nice to have a fix, but IMHO it's bad practise anyway.

**Comment by carltongibson** [comment]
Comment by @jdunck from https://github.com/django-compressor/django-compressor/issues/333#issuecomment-84460502

> I believe I have found the root cause.
>
> The issue is that loading settings can be reentrant, so that LazySettings._setup gets called twice.
> 
> This means that AppConfMetaClass's holder refers to an object that doesn't end up being the LazySettings._wrapped object. setattr(new_class._meta.holder, prefixed_name, value) modifies an object that ends up not being the final settings.

@jdunck: I need to get my head fully round your post there. Fancy inputting here?

**Comment by carltongibson** [comment]
@diox It may be a "Don't do that" is enough, but I'm happy to explore for a small bit. (I might learn something. 😀)

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment — I can't see anything straight-forward we can do. 

Don't put more than settings in you settings files.

(If anyone has a solution to offer I'm very happy to look at it but it's not something we're going to work on.)

**Comment by petervanderdoes** [comment]
A very old problem but I just ran into it and might give more insight.

We have settings files that import from other settings files, they have methods in it and all. We never had an issue with Compress until a few days ago.

What we changed is the autoload of template tags. We have a project that runs Django 1.7 (I know, I know). We use the add_to_builtins method to autload the template tags. We used to do this in the urls.py but ran into some issues with celery not autoloading the tags, so we moved it around

First we added it to the `__init__.py` of the app, which made it the autoload work but we ran into the problem with compress settings being unavailable.
Moving the autoload to the end of the settings file did not solve this problem either.

With Django 1.9 you can autoload the tags in the TEMPLATE settings, not sure if that solves the problem. Or if that remains the same problem.

My guess loading the template tags of compressor before Appconf has ran it messes with the default values.
