### ISSUE TITLE
Do you need a new maintainer?

### ISSUE THREAD

**Issue by carltongibson** [django-compressor/django-appconf#20]
Hello. 

I use Django Compressor so rely on AppConf. 

Do you need a maintainer here? (Currently doing DRF, Django Filter and Crispy Forms — I'm happy to take this on — since I've a vested interest.)

**Comment by diox** [comment]
Also happy to help here. My time is super limited but since I'm already maintaining compressor I can also help maintain django-appconf

**Comment by jezdez** [comment]
Thanks for the offer, should we move the app to the django-compressor org?

**Comment by carltongibson** [comment]
Seems sensible. I'd need an invite there but I'm happy to help.

**Comment by diox** [comment]
Moving it to the compressor org would be great, yeah. Then I can give access to @carltongibson

**Comment by jezdez** [comment]
Ok, moved it to the org.
