### ISSUE TITLE
Take over pypi package and readthedocs

### ISSUE THREAD

**Issue by simonsmiley** [django-compressor/django-appconf#22]
the documentation is till tied to the old repo, so is the pypi package

**Comment by jezdez** [comment]
The PyPI package will just link to the old URL which GitHub redirects nowadays. I let the others @carltongibson and @diox fix the URLs in the source code, including the Travis-CI URL.

I've updated RTD to use the new location.

**Comment by carltongibson** [comment]
Thanks!
