### ISSUE TITLE
Is this still being maintained? I am using Django 1.11

### ISSUE THREAD

**Issue by simkimsia** [django-compressor/django-appconf#42]

**Comment by karyon** [comment]
Not actively, but there are still people around who can merge PRs. Is there anything you've been looking at in particular?

**Comment by carltongibson** [comment]
Or yes. 😄 Zero issues currently. (Bar this one, which I'm going to close.)

**Comment by simkimsia** [comment]
Thanks 🙏

So the next version of django this library will still be working with it? I am thinking abt the next Long term support version 2.2

KimSia kimsia@oppoin.com https://simkimsia.com ( https://simkimsia.com/ )

P.S. What I'm doing now: https://simkimsia.com/now

**Comment by karyon** [comment]
it will probably just work, given that django does not look like it does any radical changes anymore. if it does not work, i'd say there's a high chance that a PR fixing that would be accepted :)

**Comment by simkimsia** [comment]
👍

KimSia kimsia@oppoin.com https://simkimsia.com ( https://simkimsia.com/ )

P.S. What I'm doing now: https://simkimsia.com/now
