### ISSUE TITLE
Compatibility with diffsettings?

### ISSUE THREAD

**Issue by pakal** [django-compressor/django-appconf#49]
Hello,

I was nicely surprised to see that django apps using AppConf showed all their settings nicely in "manage.py diffsetting", imho that's a killer feature compared to all apps which hide their defaults in handmade "getattr(settings, x, default)" calls.

Maybe it'd be worth mentioning it in docs?

Would it be feasible to also make appconf inject default settings in "global_settings" of django, so that diffsettings also shows which app settings were overriden compare to their appconf defaults (with the "###")?

**Comment by carltongibson** [comment]
Hi @pakal. Very happy to take a PR adding this to the docs! 🙂

**Comment by pakal** [comment]
Tiny PR here : https://github.com/django-compressor/django-appconf/pull/69

I've added a note about new ready() hook, I guess it's ok this way?
