### ISSUE TITLE
pypi sdist doesn't contain tests

### ISSUE THREAD

**Issue by dvzrv** [django-compressor/django-appconf#54]
When packaging 1.0.3 for Arch Linux I tried to run the tests, but they're not included in the pypi sdist.

Tests are important, especially on a distribution packaging level, as that way one can ensure, that the components integrate with the system.

**Comment by carltongibson** [comment]
I think I'm missing some background info, but I don't quite get OS packaging of packages like this, vs pip, but... Do you not pull from GitHub to build your packages?

**Comment by dvzrv** [comment]
@carltongibson thanks for getting back to me on this.

> I think I'm missing some background info, but I don't quite get OS packaging of packages like this, vs pip, but...

On a Linux distribution python packages can be installed with the system package manager (e.g. pacman in the case of Arch Linux, apt in the case of Debian, etc.).
The large difference is, that packages are installed to [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) compliant location, accessible for every user on the system.
The upside is, that all files on the file system can be tracked by the package manager. Rebuilds against a new python version can be done for all packages at the same time.

> Do you not pull from GitHub to build your packages?

We can, but it's not necessarily encouraged (as the source tarballs don't have unique enough names and in cases where there are submodules, data is missing), unless there are compelling reasons: Missing but required data in the pypi sdists, (PGP) verification for tarballs or tags/commits only provided on github.

That being said: Providing tests alongside the source code is as standard as providing LICENSE files.

**Comment by carltongibson** [comment]
> Providing tests alongside the source code is as standard as providing LICENSE files.

Not quite sure that's true, but... :)
