### ISSUE TITLE
Could we get a release for 1.0.4 for Django 2.2+?

### ISSUE THREAD

**Issue by karally** [django-compressor/django-appconf#58]
Django 1.11 is reaching EOL soon. Is it possible to get a new release that includes official support for Django 2.2?

Thank you!

**Comment by carltongibson** [comment]
OK, yes. But, just so you realise, there are zero code changes on `master`, just tests and PyPI metadata. (1.0.3 is already compatible.)

**Comment by karally** [comment]
Ah, thank you for confirming! I can stick to 1.0.3 for now then.

**Comment by carltongibson** [comment]
Available on PyPI now. 
https://pypi.org/project/django-appconf/1.0.4/
