### ISSUE TITLE
update to 1.0.4 failed project

### ISSUE THREAD

**Issue by rshch1** [django-compressor/django-appconf#64]
Hi, after your update from 1.0.3 to 1.0.4, my pipeline in project are failing.

```
  File "/home/user/projects/project/venv/local/lib/python2.7/site-packages/appconf/base.py", line 107
    class AppConf(metaclass=AppConfMetaClass):
                           ^
SyntaxError: invalid syntax
```
I had resolve my problem with downgrade version of package, but i think you need to fix it.

Python 2.7
Django 1.11

**Comment by carltongibson** [comment]
Duplicate of #59
