### ISSUE TITLE
1.0.4 wheel erroneously says that it supports Py2

### ISSUE THREAD

**Issue by native-api** [django-compressor/django-appconf#71]
At https://travis-ci.community/t/syntaxerror-fails-ci-build-in-appconf-instantiation-with-metaclass/8351, a user reported a problem that resulted from trying to run [`1.0.4`](https://pypi.org/project/django-appconf/1.0.4/#files) in Py2.

However, if that version doesn't support Py2, it shouldn't have been installed in the first place.

It turns out that the wheel's name and its metadata by which Pip picks wheels (`WHEEL` in particular) still erroneously says that it supports Py2.

**Comment by siovene** [comment]
I have the same problem, upgrading from `1.0.2` to `1.0.4` broke my build as follows:

```
File "/usr/local/lib/python2.7/dist-packages/appconf/base.py", line 107
--
978 | class AppConf(metaclass=AppConfMetaClass):
979 | ^
980 | SyntaxError: invalid syntax
```

Is it possible to maintain Python 2 support? Or at least, not break it on a patch-level release? :)

Thank you!
