### ISSUE TITLE
How does `django-appconf` interact with "Automatic `AppConfig` discovery" in Django 3.2?

### ISSUE THREAD

**Issue by allanlewis** [django-compressor/django-appconf#77]
The [Django 3.2 release notes][1] describe the following new feature:

> **Automatic `AppConfig` discovery**
>
> Most pluggable applications define an `AppConfig` subclass in an `apps.py` submodule. Many define a `default_app_config` variable pointing to this class in their `__init__.py`.
>
> When the `apps.py` submodule exists and defines a single `AppConfig` subclass, Django now uses that configuration automatically, so you can remove `default_app_config`.

[1]: https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery

Does this make `django-appconf` redundant for Django 3.2+?

**Comment by carltongibson** [comment]
They're totally unrelated classes. It's just an accident of history that they're named the same.

**Comment by carltongibson** [comment]
`AppConfig` (here) is about providing custom settings for your app.

**Comment by allanlewis** [comment]
Thanks, @carltongibson - got it 👍
