### ISSUE TITLE
Add Python 3.9 to tox run. 

### ISSUE THREAD

**Issue by carltongibson** [django-compressor/django-appconf#79]
Follow up from #78. 

I had to drop PY39 as it wasn't installing properly in tox. 

```
envlist =
    flake8-py39,
    py{36,37,38}-dj{22,31,32},
    py{38}-dj{main}
```

Just need to add the `,39`s in the two `py{...}` declarations there to run it. 

See https://github.com/django-compressor/django-appconf/runs/3394353179?check_suite_focus=true#step:5:43 for log.

**Comment by jerinpetergeorge** [comment]
it seems like an issue with the `coverage` command (same as https://github.com/nedbat/coveragepy/issues/862 ? :thinking: that fixed in [v5.0.3](https://coverage.readthedocs.io/en/latest/changes.html#version-5-0-3-2020-01-12)). I was able to run the tests without **_`coverage`_** command
