### ISSUE TITLE
Do there any blockers to bump new release?

### ISSUE THREAD

**Issue by jramnai** [django-compressor/django-appconf#83]
We are looking forward to using `django-appconf` with Django 3.2 on [edX](https://github.com/edx).

Develop branch is already tested against Django 3.2.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by carltongibson** [comment]
It's on my list for ~~this week~~ after the Django 4.0 feature freeze as it happens. There are no changes that are anything other than metadata related. 

You should be good to update, as you'd see if you install the latest with Django 3.2 and run the edX test suite. If there were failures an issue report would be useful.

**Comment by jramnai** [comment]
> It's on my list for this week as it happens.

That's great! Thanks!

**Comment by manchandavishal** [comment]
Hi @carltongibson any update on new release?

**Comment by carltongibson** [comment]
Yes, I've decided to wait for the Django 4.0 alpha, which will be released soon, so that we can declare 4.0 compatibility now, and not have the same issue then.
