### ISSUE TITLE
Document `configure_` functionality

### ISSUE THREAD

**Issue by thismatters** [django-compressor/django-appconf#88]
The docs make no mention of the functionality for configuring settings, which is a pretty useful feature to be aware of. 

I've seen this functionality used out in the wild, and have confirmed that it exists in codebase, but it cannot be found in the docs!

**Comment by carltongibson** [comment]
Would you like to suggest an addition @thismatters?

**Comment by thismatters** [comment]
Sure, I'll make a pull request!

**Comment by thismatters** [comment]
Oh, after cloning the code and locating where the update should go I noticed that the documentation is already written (and hosted correctly on the [readthedocs](https://django-appconf.readthedocs.io/en/latest/usage/#custom-configuration) page); I hadn't noticed that a readthedocs existed for this tool, and had been working solely off the short-form documentation on PyPI. Forgive my ignorance and accept my apology for crufting up your board!

**Comment by carltongibson** [comment]
Thanks for the follow up. We do aim for 0 😜


If you have a change that would have allowed you to spot the docs more easily, I'd happily look at that too...
