### ISSUE TITLE
Test against Django 4.2a1

### ISSUE THREAD

**Issue by chambersh1129** [django-compressor/django-appconf#89]
Per [Carlton Gibson](https://fosstodon.org/@carlton/109706012212452279), I'd like to submit a PR to add Django 4.2 support.  From what I can tell it is just updating tox.ini and verifying tests pass, let me know if there is more to do.

**Comment by carltongibson** [comment]
That's it. Thanks! 

Plus we could add the Trove classifier to the setup.py/cfg 

Plus glancing at the docs to see if we SAY what versions are supported.

**Comment by carltongibson** [comment]
Just looking at recent commits, most of them are this kind of updating, so you should be able to follow the pattern. 

Thanks for picking this up!
