### ISSUE TITLE
Releasing a new version with Django 4.2 support

### ISSUE THREAD

**Issue by irtazaakram** [django-compressor/django-appconf#91]
When can we expect the release of the new version with Django 4.2, considering that the master branch has already been updated with 4.2a1?

Thanks,

**Comment by carltongibson** [comment]
This needs the text matrix and the Trove classifiers updated. 

There are no code changes, so it's already compatible but just needs to declare it officially.

**Comment by carltongibson** [comment]
https://pypi.org/project/django-appconf/1.0.6/ adds Trove classifiers for Django 5.0 and 4.2, and well as Python 3.12
