### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by dvzrv** [django-compressor/django-appconf#94]
Hi! :wave:

I package this project for Arch Linux. We rely on upstream source tarballs (https://rfc.archlinux.page/0020-sources-for-python-packaging/), as pypi sdist tarballs are not well-defined and often unfortunately insufficient or broken.

This project unfortunately misses the tags for the last two releases 1.0.5 and 1.0.6 and therefore downstreams can not make use of auto-generated source tarballs here on github.

Could you please add the relevant tags? Thanks! :)

**Comment by carltongibson** [comment]
Tags exist: 


https://github.com/django-compressor/django-appconf/releases/tag/v1.0.6

... for example. 

`git tag` should list them for you at the command line.

**Comment by dvzrv** [comment]
Oh, my bad. Must have tripped over them not showing alongside releases on the right side of the page.

Sorry for the noise! :sweat_smile:

**Comment by carltongibson** [comment]
No problem. Thanks for your effort 🎁

**Comment by carltongibson** [comment]
Oh, I've turned off "Releases" &co on the repo settings, so they shouldn't appear again. PyPI is the canonical source
